jobs:
  build-docker:
    name: Build and push Docker image to Docker Hub
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: gcr.io/xpn-heroic-1/heroic
        tag-sha: true
    - continue-on-error: true
      uses: docker/setup-buildx-action@v1
    - continue-on-error: true
      uses: docker/login-action@v1
      with:
        password: ${{ secrets.GCR_JSON_KEY }}
        registry: gcr.io
        username: _json_key
    - continue-on-error: true
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: ${{ steps.docker_meta.outputs.tags }}
name: Docker build workflow
on:
  repository_dispatch:
    types: trigger-ga___docker-build.yml
